In [1]:
mes_notes=[19,7,15,9,10,6,18,10,16,14,13,10,2,20,17,8,12,10,11,4]

In [5]:
import numpy

In [15]:
mes_notes

[19, 7, 15, 9, 10, 6, 18, 10, 16, 14, 13, 10, 2, 20, 17, 8, 12, 10, 11, 4]

In [18]:
moyenne_generale=numpy.mean(mes_notes)
moyenne_generale

11.55

In [22]:
min(mes_notes)

2

In [23]:
max(mes_notes)

20

In [25]:
mes_notes.sort()
mes_notes

[2, 4, 6, 7, 8, 9, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [26]:
mes_notes.reverse()
mes_notes

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 2]

In [27]:
mes_notes.sort()
mes_notes

[2, 4, 6, 7, 8, 9, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [28]:
help(mes_notes.sort)

Help on built-in function sort:

sort(*, key=None, reverse=False) method of builtins.list instance
    Sort the list in ascending order and return None.

    The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
    order of two equal elements is maintained).

    If a key function is given, apply it once to each list item and sort them,
    ascending or descending, according to their function values.

    The reverse flag can be set to sort in descending order.



In [30]:
mes_notes.sort(reverse=True)
mes_notes

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 2]

In [31]:
mes_notes[19]=6
mes_notes

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 6]

In [32]:
mes_notes.count(10)

4

In [34]:
mes_notes_array=numpy.asarray(mes_notes)
mes_notes_array

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10,  9,  8,  7,
        6,  4,  6])

In [35]:
mes_notes_array[mes_notes_array>10]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [36]:
mes_notes_array>10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [37]:
len(mes_notes_array[mes_notes_array>10])

10