In [89]:
str(13)

'13'

In [90]:
"1" + "3"

'13'

In [92]:
"1"+"3"

'13'

'1'+'3'

In [93]:
'1'+'3'


'13'

# 

In [97]:
'1'+'3'

'13'

In [98]:
6+7

13

In [99]:
# voici comment faire une opération 

In [100]:
## voici comment faire une opération avec une plus grande typo


In [101]:
14-1

13

In [102]:
5*2

10

In [103]:
12/4


3.0

In [104]:
5/3

1.6666666666666667

In [105]:
5//3

1

In [108]:
6 % 3

0

In [109]:
2**3

8

In [110]:
3**2

9

In [111]:
1*12

12

In [113]:
one_var1=10
one_var2=30
one_var2*one_var1

300

In [115]:
one_var1=10
one_var2=2
one_var1/one_var2

5.0

In [116]:
one_var1+3

13

In [117]:
one_var1*10

100

In [119]:
one_var1='C\'est le kiffe à Montmartre '
one_var1*13

"C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre C'est le kiffe à Montmartre "

In [3]:
a=13

In [121]:
print(a)


13


In [123]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [ ]:
print(a,"b")

In [4]:
print(a)

13


In [5]:
print(a,"b")

13 b


In [6]:
liste1=[1,2,3,4]

In [7]:
liste1

[1, 2, 3, 4]

In [8]:
# mean
import numpy

In [9]:
numpy.mean(liste1)


2.5

In [10]:
help(numpy.mean)


Help on _ArrayFunctionDispatcher in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For

In [11]:
dir(numpy)


['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [12]:
numpy.min(liste1)

1

In [14]:
numpy.max(liste1)

4

In [15]:
1a=2

SyntaxError: invalid decimal literal (3431396677.py, line 1)

In [16]:
a1=2

In [17]:
a1

2

In [19]:
liste1=[1,2,3,4, "hello", 10.5]

In [20]:
liste1


[1, 2, 3, 4, 'hello', 10.5]

In [21]:
print(liste1)

[1, 2, 3, 4, 'hello', 10.5]


In [22]:
liste1[0]

1

In [25]:
liste1[0:5]

[1, 2, 3, 4, 'hello']

In [26]:
liste1[3:]

[4, 'hello', 10.5]

In [28]:
liste1[0:2],liste1[3],liste1[4:6]

([1, 2], 4, ['hello', 10.5])

In [29]:
liste1[-1]

10.5

In [30]:
liste1[-2]

'hello'

In [31]:
liste1[1:-2]

[2, 3, 4]

In [36]:
liste1[0:-4]

[1, 2]

In [37]:
liste1[::2]

[1, 3, 'hello']

In [39]:
liste1[1::3]

[2, 'hello']

In [44]:
liste1.append(555)
    

In [49]:
print(liste1)


[1, 2, 3, 4, 'hello', 10.5, 555, 'Sacré coeur trop cool', 'yess un nouvel appartement', 555]


In [46]:
liste1.insert(8, "yess un nouvel appartement")


In [50]:
liste1[3:5]=["Sacré coeur trop cool", "Quelle chance"]


In [51]:
print(liste1)

[1, 2, 3, 'Sacré coeur trop cool', 'Quelle chance', 10.5, 555, 'Sacré coeur trop cool', 'yess un nouvel appartement', 555]


In [52]:
liste1[5:7]=[333, 444]

In [53]:
print(liste1)


[1, 2, 3, 'Sacré coeur trop cool', 'Quelle chance', 333, 444, 'Sacré coeur trop cool', 'yess un nouvel appartement', 555]


In [56]:
liste1[5:8]=[]

In [57]:
print(liste1)

[1, 2, 3, 'Sacré coeur trop cool', 'Quelle chance']


In [58]:
del liste1[1]

In [59]:
print(liste1)

[1, 3, 'Sacré coeur trop cool', 'Quelle chance']


In [61]:
liste2=[1,2,3,4,5]
liste3=[6,7,8,9,10]
liste4=liste2+liste3
liste4

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [62]:
sum(liste2)
sum(liste3)
sum(liste4)

55

In [63]:
sum(liste3)

40

In [65]:
len(liste4)

10

In [66]:
liste5=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 5, 5]

In [67]:
liste5.count(5)

3

In [71]:
liste5.sort()
liste5

[1, 2, 3, 4, 5, 5, 5, 6, 7, 8, 9, 10]

In [72]:
liste5.reverse()
liste5

[10, 9, 8, 7, 6, 5, 5, 5, 4, 3, 2, 1]

In [73]:
min(liste5)

1

In [74]:
max(liste5)

10

In [75]:
tuple1=(1, 2, 3, 4, 5)
tuple1

(1, 2, 3, 4, 5)

In [76]:
tuple1[0]=0

TypeError: 'tuple' object does not support item assignment

In [79]:
tuple1[4]

5

In [80]:
mes_notes=[19,7,15,9,10,6,18,10,16,14,13,10,2,20,17,8,12,10,11,4]

In [85]:
globalAverage=sum(mes_notes)/len(mes_notes)
globalAverage


11.55

In [86]:
min(mes_notes)

2

In [87]:
max(mes_notes)

20

In [89]:
mes_notes.sort()
mes_notes

[2, 4, 6, 7, 8, 9, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [90]:
mes_notes[0]=6
mes_notes

[6, 4, 6, 7, 8, 9, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [91]:
mes_notes.count(10)

4

In [97]:
mes_notes.count(>=11)

SyntaxError: invalid syntax (1257632666.py, line 1)

In [98]:
mes_notes_array=numpy.asarray(mes_notes)

In [99]:
mes_notes_array

array([ 6,  4,  6,  7,  8,  9, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [100]:
mes_notes_array[mes_notes_array>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [101]:
mes_notes_array>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])