In [10]:
# pour lire le fichier Houses.csv il faut créer une variable et utiliser np.genfromtext("Chaine de caractère du nom de fichier à lire") 
# Houses.csv qui est bien dans le même répertoire de travail que le notesBook  de travail en cours
# extension csv  +  np.genfromtext
# ce fichier va s'ouvrir dans un nparray avec un délimiteur dont la valeur est une virgule et on lui donne un type de données ici des entiers

import numpy as np

In [11]:
houses = np.genfromtxt("Houses.csv", delimiter=",", dtype=int)

In [14]:
houses
# 20 lignes 3 col --> jeu de données qui contient la vente de 20 maisons dans une city américaine en 2008
# prix de vente des maisons dans la col 1, col 2 surface maisons, col 3 taille terrain -->> le tout en dollars et unités de mesure américaine (pied)

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

In [26]:
np.multiply(houses, 0.86)

array([[182320.  ,   3567.28,  21727.04],
       [197800.  ,   2150.86,  10226.26],
       [291540.  ,   3761.64,  21801.86],
       [248540.  ,   2062.28,  19104.9 ],
       [137600.  ,   2180.96,   7941.24],
       [ 73100.  ,   2036.48,  11462.94],
       [ 73100.  ,   1087.04,   7230.02],
       [124700.  ,   1351.92,  10825.68],
       [141040.  ,   2042.5 ,  13935.44],
       [106210.  ,    998.46,   8278.36],
       [154800.  ,   1326.12,   7529.3 ],
       [137170.  ,   1259.04,  12586.96],
       [134160.  ,   1926.4 ,  18730.8 ],
       [125990.  ,   1091.34,   9675.  ],
       [ 87290.  ,    794.64,   6330.46],
       [ 94428.  ,    660.48,   9027.42],
       [156520.  ,   1135.2 ,  13560.48],
       [ 94600.  ,   1586.7 ,  10451.58],
       [107500.  ,   1095.64,  11725.24],
       [ 68800.  ,   1638.3 ,   9365.4 ]])

In [119]:
#  1 Convertir le prix des maisons en euros, sachant que 1 dollar = 0.86 euros CORRECTION

houses[:,0]=houses[:,0] * 0.86

In [31]:
#  1 Convertir le prix des maisons en euros, sachant que 1 dollar = 0.86 euros
prix_des_maisons_en_euros=np.multiply(houses[:,0], 0.86)
prix_des_maisons_en_euros

array([182320., 197800., 291540., 248540., 137600.,  73100.,  73100.,
       124700., 141040., 106210., 154800., 137170., 134160., 125990.,
        87290.,  94428., 156520.,  94600., 107500.,  68800.])

In [38]:
np.multiply(houses, 0.9)
# calcul des aires appliqués faussement aux trois colonnes

array([[190800. ,   3733.2,  22737.6],
       [207000. ,   2250.9,  10701.9],
       [305100. ,   3936.6,  22815.9],
       [260100. ,   2158.2,  19993.5],
       [144000. ,   2282.4,   8310.6],
       [ 76500. ,   2131.2,  11996.1],
       [ 76500. ,   1137.6,   7566.3],
       [130500. ,   1414.8,  11329.2],
       [147600. ,   2137.5,  14583.6],
       [111150. ,   1044.9,   8663.4],
       [162000. ,   1387.8,   7879.5],
       [143550. ,   1317.6,  13172.4],
       [140400. ,   2016. ,  19602. ],
       [131850. ,   1142.1,  10125. ],
       [ 91350. ,    831.6,   6624.9],
       [ 98820. ,    691.2,   9447.3],
       [163800. ,   1188. ,  14191.2],
       [ 99000. ,   1660.5,  10937.7],
       [112500. ,   1146.6,  12270.6],
       [ 72000. ,   1714.5,   9801. ]])

In [120]:
# 2 Convertir les pieds carrés en mètres carrés, sachant que 1 pied carré = 0.09 m². 
surfaces_en_metres_carres=np.multiply(houses[:,1:], 0.9)
surfaces_en_metres_carres

# CORRECTION houses[:,1]=houses[:,] * 0.09

array([[ 3733.2, 22737.6],
       [ 2250.9, 10701.9],
       [ 3936.6, 22815.9],
       [ 2158.2, 19993.5],
       [ 2282.4,  8310.6],
       [ 2131.2, 11996.1],
       [ 1137.6,  7566.3],
       [ 1414.8, 11329.2],
       [ 2137.5, 14583.6],
       [ 1044.9,  8663.4],
       [ 1387.8,  7879.5],
       [ 1317.6, 13172.4],
       [ 2016. , 19602. ],
       [ 1142.1, 10125. ],
       [  831.6,  6624.9],
       [  691.2,  9447.3],
       [ 1188. , 14191.2],
       [ 1660.5, 10937.7],
       [ 1146.6, 12270.6],
       [ 1714.5,  9801. ]])

In [124]:
# 3 Combien de maisons ont un terrain de plus de 1000 m²?

# ensemble des terrains en mètres carrés 
surface_des_terrains_en_metres_carres=np.multiply(houses[:,2], 0.9)

# CORRECTION len(houses[houses[:,2]>10000])

In [123]:
len(houses[houses[:,2]>10000])

15

In [70]:
surface_des_terrains_en_metres_carres

array([22737.6, 10701.9, 22815.9, 19993.5,  8310.6, 11996.1,  7566.3,
       11329.2, 14583.6,  8663.4,  7879.5, 13172.4, 19602. , 10125. ,
        6624.9,  9447.3, 14191.2, 10937.7, 12270.6,  9801. ])

In [76]:
surface_des_terrains_en_metres_carres[surface_des_terrains_en_metres_carres > 1000]

array([22737.6, 10701.9, 22815.9, 19993.5, 11996.1, 11329.2, 14583.6,
       13172.4, 19602. , 10125. , 14191.2, 10937.7, 12270.6])

In [88]:
# 4 Calculer la somme totale obtenue après la vente des 20 maisons.
# help(np.sum)
somme_3_colonnes=np.sum(houses, axis=0)
print(somme_3_colonnes)

[3182800   39248  280833]


In [90]:
print("la somme des ventes des 20 maisons est de %d dollars" +  (somme_3_colonnes[0]))

TypeError: can only concatenate str (not "numpy.int32") to str

In [92]:
print("la somme des ventes des 20 maisons est de %d dollars. Yees concat réussie !" % somme_3_colonnes[0])

la somme des ventes des 20 maisons est de 3182800 dollars. Yees concat réussie !


In [132]:
# Exemple de tableau NumPy (chaque ligne représente une maison)
houses = np.array([
    [212000, 4148, 25264],
    [230000, 2501, 11891],
    [339000, 4374, 25351],
    [289000, 2398, 22215],
    [160000, 2536, 9234],
    [85000, 2368, 13329],
    [85000, 1264, 8407],
    [145000, 1572, 12588],
    [164000, 2375, 16204],
    [123500, 1161, 9626],
    [180000, 1542, 8755],
    [159500, 1464, 14636],
    [156000, 2240, 21780],
    [146500, 1269, 11250],
    [101500, 924, 7361],
    [109800, 768, 10497],
    [182000, 1320, 15768],
    [110000, 1845, 12153],
    [125000, 1274, 13634],
    [80000, 1905, 10890]
])


In [133]:
# 4 Calculer la somme totale obtenue après la vente des 20 maisons.
# help(np.sum)
# CORRECTION

np.sum(houses[:,0])

3182800

In [96]:
# help(np.sort)
# help(np.max)

In [98]:
# valeur maximum dans toutes les dimensions du tableau
houses.max()

339000

In [134]:
# QUELLE EST LA TAILLE DE LA MAISON VENDUE LA PLUS CHERE
# 1. Trouver l'indice de la valeur maximale dans la première colonne (prix)
indice_max_colonne_ventes = houses[:, 0].argmax()

# 2. Utiliser cet indice pour accéder à la valeur correspondante dans la troisième colonne (surface du terrain)
troisieme_colonne_surface_terrains = houses[indice_max_colonne_ventes, 2]

# 3. Afficher la surface du terrain de la maison vendue la plus chère
print(f"La surface du terrain de la maison vendue la plus chère est de : {troisieme_colonne_surface_terrains} pieds carrés")


La surface du terrain de la maison vendue la plus chère est de : 25351 pieds carrés


In [135]:
# QUELLE EST LA TAILLE DE LA MAISON VENDUE LA PLUS CHERE Correction
prix_max=np.max(houses[:,0])
print(prix_max)

339000


In [136]:
houses[houses[:,0] == prix_max]

array([[339000,   4374,  25351]])

In [113]:
# 6 Juste pour l’exercice, splitter (casser) l’array en trois tableaux, puis les concaténer à nouveau pour obtenir le tableau initial.
np.split(houses,[2,6])

[array([[212000,   4148,  25264],
        [230000,   2501,  11891]]),
 array([[339000,   4374,  25351],
        [289000,   2398,  22215],
        [160000,   2536,   9234],
        [ 85000,   2368,  13329]]),
 array([[ 85000,   1264,   8407],
        [145000,   1572,  12588],
        [164000,   2375,  16204],
        [123500,   1161,   9626],
        [180000,   1542,   8755],
        [159500,   1464,  14636],
        [156000,   2240,  21780],
        [146500,   1269,  11250],
        [101500,    924,   7361],
        [109800,    768,  10497],
        [182000,   1320,  15768],
        [110000,   1845,  12153],
        [125000,   1274,  13634],
        [ 80000,   1905,  10890]])]

In [138]:
# correction split en trois sur la ligne horizontale pour garder les trois colonne
prix,taille_maison,taille_terrain=np.hsplit(houses,3)

In [139]:
print(prix,taille_maison,taille_terrain)

[[212000]
 [230000]
 [339000]
 [289000]
 [160000]
 [ 85000]
 [ 85000]
 [145000]
 [164000]
 [123500]
 [180000]
 [159500]
 [156000]
 [146500]
 [101500]
 [109800]
 [182000]
 [110000]
 [125000]
 [ 80000]] [[4148]
 [2501]
 [4374]
 [2398]
 [2536]
 [2368]
 [1264]
 [1572]
 [2375]
 [1161]
 [1542]
 [1464]
 [2240]
 [1269]
 [ 924]
 [ 768]
 [1320]
 [1845]
 [1274]
 [1905]] [[25264]
 [11891]
 [25351]
 [22215]
 [ 9234]
 [13329]
 [ 8407]
 [12588]
 [16204]
 [ 9626]
 [ 8755]
 [14636]
 [21780]
 [11250]
 [ 7361]
 [10497]
 [15768]
 [12153]
 [13634]
 [10890]]


In [141]:
# correction concatenation
houses_original=np.concatenate([prix,taille_maison,taille_terrain], axis =1 )
print(houses_original)

[[212000   4148  25264]
 [230000   2501  11891]
 [339000   4374  25351]
 [289000   2398  22215]
 [160000   2536   9234]
 [ 85000   2368  13329]
 [ 85000   1264   8407]
 [145000   1572  12588]
 [164000   2375  16204]
 [123500   1161   9626]
 [180000   1542   8755]
 [159500   1464  14636]
 [156000   2240  21780]
 [146500   1269  11250]
 [101500    924   7361]
 [109800    768  10497]
 [182000   1320  15768]
 [110000   1845  12153]
 [125000   1274  13634]
 [ 80000   1905  10890]]


In [115]:
np.concatenate(houses)

array([212000,   4148,  25264, 230000,   2501,  11891, 339000,   4374,
        25351, 289000,   2398,  22215, 160000,   2536,   9234,  85000,
         2368,  13329,  85000,   1264,   8407, 145000,   1572,  12588,
       164000,   2375,  16204, 123500,   1161,   9626, 180000,   1542,
         8755, 159500,   1464,  14636, 156000,   2240,  21780, 146500,
         1269,  11250, 101500,    924,   7361, 109800,    768,  10497,
       182000,   1320,  15768, 110000,   1845,  12153, 125000,   1274,
        13634,  80000,   1905,  10890])