In [2]:
import numpy as np

In [4]:
# on ne mélange pas les types de données dans les np arrays
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [5]:
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
mon_array_bidimensionnel=np.array([[1,2,3],[4,5,6],[7,8,9]])
mon_array_bidimensionnel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
sous_tableau=notre_tableau[0:5]
# slicing qui s'arrête une case avant [0:5]

In [11]:
sous_tableau[0]=10
sous_tableau

array([10,  2,  3,  4,  5])

In [12]:
notre_tableau
# pourquoi le sous tableau modifie - t- il le grand tableau 
# tout simplement parce que numpy est fait pour que les petits tableaux soient répercutables sur le grand tableau
# ce sont les notions de vues et copies d'un tableau --> travailler dans un sous-ensemble de tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
sous_tableau=notre_tableau[0:5].copy()
notre_tableau[0:5]

array([1, 2, 3, 4, 5])

In [17]:
sous_tableau[0]=10
sous_tableau

array([10,  2,  3,  4,  5])

In [18]:
notre_tableau
# avec la sauvegarde dans sous_tableau=notre_tableau[0:5].copy() le grand tbleau ne s'en voit pas modifié

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
# accèder aux éléments d'un array 
mon_array_bidimensionnel=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
mon_array_bidimensionnel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
mon_array_bidimensionnel[1,2]
# crochet pour atteindre les index des arrays en deux dimensions

6

In [28]:
mon_array_bidimensionnel[1,-1]

6

In [25]:
# accèder aux éléments d'un array AVEC slicing
mon_array_bidimensionnel[:,0]

array([1, 4, 7])

In [24]:
# accèder aux éléments d'un array AVEC slicing
mon_array_bidimensionnel[0,:]

array([1, 2, 3])

In [33]:
mon_array_bidimensionnel[:,0:3:2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [34]:
mon_array_bidimensionnel[:,-1]

array([3, 6, 9])

In [35]:
mon_array_bidimensionnel[:,1:-1]

array([[2],
       [5],
       [8]])

In [36]:
mon_array_bidimensionnel[2,1:-1]

array([8])

In [39]:
# fonction pour créer array bidimensionnel avec numpy et la ft randint() qui veut dire random integer
# numpy fonctionne en sous-dossiers par ex randint() est rangée dans un sous-dossier de numpy -->> random

array=np.random.randint(100, size=(6,4)) # valeur comprise entre 0 et 100, 6 lignes quatres colonnes.
array

array([[96, 35, 45, 25],
       [28, 66, 34, 75],
       [45,  7, 45, 65],
       [59, 93, 56, 45],
       [47, 74, 30, 57],
       [51, 96, 68, 75]])

In [41]:
# il ya des méthodes et des attributs spécifiques aux arrays comme ndarray.ndim ndim pour dimension
array.ndim

2

In [46]:
array.shape # autres attributs ref documentation

(6, 4)

In [47]:
array.dtype

dtype('int32')

In [48]:
array.size

24

In [49]:
# parcourir les valeurs sans boucle
array[array>50]

array([96, 66, 75, 65, 59, 93, 56, 74, 57, 51, 96, 68, 75])

In [51]:
array>50 # équivaut à faire une boucle et renvoyer  si c'est vrai ou faux

array([[ True, False, False, False],
       [False,  True, False,  True],
       [False, False, False,  True],
       [ True,  True,  True, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True]])

In [52]:
array[array==50] # il n'y a pas de valeur 50 dans le tableau

array([], dtype=int32)

In [53]:
array[array!=50]

array([96, 35, 45, 25, 28, 66, 34, 75, 45,  7, 45, 65, 59, 93, 56, 45, 47,
       74, 30, 57, 51, 96, 68, 75])

In [54]:
# & : and
# | : or
# ternaires en python exemple

array[(array >=30) & (array<=60)]

array([35, 45, 34, 45, 45, 59, 56, 45, 47, 30, 57, 51])

In [56]:
array[(array >=30) | (array<=60)]
# globalement on n'aura pas de valeur situé entre 30 et 60

array([96, 35, 45, 25, 28, 66, 34, 75, 45,  7, 45, 65, 59, 93, 56, 45, 47,
       74, 30, 57, 51, 96, 68, 75])

In [57]:
# concaténation avec numpy
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [59]:
array2=np.array([[2,5,6],[9,10,11],[5,6,9]])

In [61]:
np.concatenate([array1,array2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9]])

In [62]:
array3=np.array([[4,10,13],[7,14,15],[10,16,84]])

In [63]:
np.concatenate([array1,array2, array3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9],
       [ 4, 10, 13],
       [ 7, 14, 15],
       [10, 16, 84]])

In [65]:
# fonction vstack pour empilation verticale et hstack pour empilation horizontale
array1=np.array([15,16,47])

In [67]:
array1

array([15, 16, 47])

In [66]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [68]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.vstack([array1, array2]) # vstack attend une liste
# rajoute la valeur de array1 dans un tableau bidimensionel

array([[15, 16, 47],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [72]:
array1=np.array([[15],[16],[47]])
array1

array([[15],
       [16],
       [47]])

In [73]:
np.hstack([array1, array2]) # concatène horizontalement

array([[15,  1,  2,  3],
       [16,  4,  5,  6],
       [47,  7,  8,  9]])

In [75]:
# casser un tableau ou splitter
array=np.array([15,16,17,12,49,52,12,14,36])
len(array)

9

In [77]:
np.split(array,[2,6])
# dans la sortie les point de séparation en trois partie depuis le deuxième index, puis le sixième
# point de cassure entre crochet pour déterminer l'index

[array([15, 16]), array([17, 12, 49, 52]), array([12, 14, 36])]

In [78]:
# après le split de l'exemple ci-dessus on peut assigner les trois tableaux à trois variable auxquels on peut réappliquer des méthodes
array1,array2,array3=np.split(array,[2,6])

In [79]:
print(array1,array2,array3)

[15 16] [17 12 49 52] [12 14 36]


In [82]:
array1,array2,array3,array4=np.split(array,[2,4,6])

In [83]:
print(array1,array2,array3,array4)

[15 16] [17 12] [49 52] [12 14 36]


In [84]:
############# Abstraction compréhension split 

In [85]:
# splitter les tableaux en deux dimensions avec vsplit ou hsplit vertical/horizontal
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [90]:
array1,array1bis=np.vsplit(array2,[2])
print(array1,array1bis)
# ci-dessous la coupure du tableau est bien verticale [[7 8 9]] crée une nouvelle colonne

[[1 2 3]
 [4 5 6]] [[7 8 9]]


In [89]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
array1,array1bis=np.hsplit(array2,[2])
print(array1,array1bis)
# ici il a crée un array splitté au deuximème index -->> index 0 et 1 restent ensembles
# l'index 2 sur l'horizon du tableau se sépare en un deuxième array

[[1 2]
 [4 5]
 [7 8]] [[3]
 [6]
 [9]]


In [94]:
# opérations arithmétiques sur les tableaux
array=np.random.randint(350, size=(10,9))
array

array([[302,  33, 239, 239,  12,  75, 262,   3, 112],
       [203, 323,  92, 192,  79,  36,  25, 199, 127],
       [130, 211, 218, 136, 153, 145, 126, 289, 287],
       [ 32, 130,  19, 264, 285, 313, 110, 185,  77],
       [177, 229,  84,  84, 251, 242, 192,  99,  65],
       [ 50,   7, 308,  87, 128,  99, 291, 221, 336],
       [ 54, 132, 268, 174,  79, 292,  63,   5, 181],
       [266,  15, 297, 148, 151,  74, 141, 264, 300],
       [159,  69, 117,  86,  71, 321,  89, 242,  57],
       [120, 192, 296, 339,  16,  47, 217, 265,  51]])

In [95]:
# incrémenter toutes les valeurs du tableau ex incrémentation de'un pas de 2
array+2

array([[304,  35, 241, 241,  14,  77, 264,   5, 114],
       [205, 325,  94, 194,  81,  38,  27, 201, 129],
       [132, 213, 220, 138, 155, 147, 128, 291, 289],
       [ 34, 132,  21, 266, 287, 315, 112, 187,  79],
       [179, 231,  86,  86, 253, 244, 194, 101,  67],
       [ 52,   9, 310,  89, 130, 101, 293, 223, 338],
       [ 56, 134, 270, 176,  81, 294,  65,   7, 183],
       [268,  17, 299, 150, 153,  76, 143, 266, 302],
       [161,  71, 119,  88,  73, 323,  91, 244,  59],
       [122, 194, 298, 341,  18,  49, 219, 267,  53]])

In [97]:
array-2

array([[300,  31, 237, 237,  10,  73, 260,   1, 110],
       [201, 321,  90, 190,  77,  34,  23, 197, 125],
       [128, 209, 216, 134, 151, 143, 124, 287, 285],
       [ 30, 128,  17, 262, 283, 311, 108, 183,  75],
       [175, 227,  82,  82, 249, 240, 190,  97,  63],
       [ 48,   5, 306,  85, 126,  97, 289, 219, 334],
       [ 52, 130, 266, 172,  77, 290,  61,   3, 179],
       [264,  13, 295, 146, 149,  72, 139, 262, 298],
       [157,  67, 115,  84,  69, 319,  87, 240,  55],
       [118, 190, 294, 337,  14,  45, 215, 263,  49]])

In [98]:
array * 10

array([[3020,  330, 2390, 2390,  120,  750, 2620,   30, 1120],
       [2030, 3230,  920, 1920,  790,  360,  250, 1990, 1270],
       [1300, 2110, 2180, 1360, 1530, 1450, 1260, 2890, 2870],
       [ 320, 1300,  190, 2640, 2850, 3130, 1100, 1850,  770],
       [1770, 2290,  840,  840, 2510, 2420, 1920,  990,  650],
       [ 500,   70, 3080,  870, 1280,  990, 2910, 2210, 3360],
       [ 540, 1320, 2680, 1740,  790, 2920,  630,   50, 1810],
       [2660,  150, 2970, 1480, 1510,  740, 1410, 2640, 3000],
       [1590,  690, 1170,  860,  710, 3210,  890, 2420,  570],
       [1200, 1920, 2960, 3390,  160,  470, 2170, 2650,  510]])

In [102]:
# opérations arithmétiques sur une colonne ou ligne en particulier
array[:,0] * 10
# ici il'sgit bien d'un slice ex sortie ci-dessous

array([3020, 2030, 1300,  320, 1770,  500,  540, 2660, 1590, 1200])

In [103]:
array / 2

array([[151. ,  16.5, 119.5, 119.5,   6. ,  37.5, 131. ,   1.5,  56. ],
       [101.5, 161.5,  46. ,  96. ,  39.5,  18. ,  12.5,  99.5,  63.5],
       [ 65. , 105.5, 109. ,  68. ,  76.5,  72.5,  63. , 144.5, 143.5],
       [ 16. ,  65. ,   9.5, 132. , 142.5, 156.5,  55. ,  92.5,  38.5],
       [ 88.5, 114.5,  42. ,  42. , 125.5, 121. ,  96. ,  49.5,  32.5],
       [ 25. ,   3.5, 154. ,  43.5,  64. ,  49.5, 145.5, 110.5, 168. ],
       [ 27. ,  66. , 134. ,  87. ,  39.5, 146. ,  31.5,   2.5,  90.5],
       [133. ,   7.5, 148.5,  74. ,  75.5,  37. ,  70.5, 132. , 150. ],
       [ 79.5,  34.5,  58.5,  43. ,  35.5, 160.5,  44.5, 121. ,  28.5],
       [ 60. ,  96. , 148. , 169.5,   8. ,  23.5, 108.5, 132.5,  25.5]])

In [105]:
# numpy a des fonctions avec des opérateurs arithmètiques fiable comme add() etc...
np.add(array,5)

array([[307,  38, 244, 244,  17,  80, 267,   8, 117],
       [208, 328,  97, 197,  84,  41,  30, 204, 132],
       [135, 216, 223, 141, 158, 150, 131, 294, 292],
       [ 37, 135,  24, 269, 290, 318, 115, 190,  82],
       [182, 234,  89,  89, 256, 247, 197, 104,  70],
       [ 55,  12, 313,  92, 133, 104, 296, 226, 341],
       [ 59, 137, 273, 179,  84, 297,  68,  10, 186],
       [271,  20, 302, 153, 156,  79, 146, 269, 305],
       [164,  74, 122,  91,  76, 326,  94, 247,  62],
       [125, 197, 301, 344,  21,  52, 222, 270,  56]])

In [107]:
np.subtract(array,1)

array([[301,  32, 238, 238,  11,  74, 261,   2, 111],
       [202, 322,  91, 191,  78,  35,  24, 198, 126],
       [129, 210, 217, 135, 152, 144, 125, 288, 286],
       [ 31, 129,  18, 263, 284, 312, 109, 184,  76],
       [176, 228,  83,  83, 250, 241, 191,  98,  64],
       [ 49,   6, 307,  86, 127,  98, 290, 220, 335],
       [ 53, 131, 267, 173,  78, 291,  62,   4, 180],
       [265,  14, 296, 147, 150,  73, 140, 263, 299],
       [158,  68, 116,  85,  70, 320,  88, 241,  56],
       [119, 191, 295, 338,  15,  46, 216, 264,  50]])

In [108]:
np.multiply(array,2)

array([[604,  66, 478, 478,  24, 150, 524,   6, 224],
       [406, 646, 184, 384, 158,  72,  50, 398, 254],
       [260, 422, 436, 272, 306, 290, 252, 578, 574],
       [ 64, 260,  38, 528, 570, 626, 220, 370, 154],
       [354, 458, 168, 168, 502, 484, 384, 198, 130],
       [100,  14, 616, 174, 256, 198, 582, 442, 672],
       [108, 264, 536, 348, 158, 584, 126,  10, 362],
       [532,  30, 594, 296, 302, 148, 282, 528, 600],
       [318, 138, 234, 172, 142, 642, 178, 484, 114],
       [240, 384, 592, 678,  32,  94, 434, 530, 102]])

In [110]:
np.divide(array,10)

array([[30.2,  3.3, 23.9, 23.9,  1.2,  7.5, 26.2,  0.3, 11.2],
       [20.3, 32.3,  9.2, 19.2,  7.9,  3.6,  2.5, 19.9, 12.7],
       [13. , 21.1, 21.8, 13.6, 15.3, 14.5, 12.6, 28.9, 28.7],
       [ 3.2, 13. ,  1.9, 26.4, 28.5, 31.3, 11. , 18.5,  7.7],
       [17.7, 22.9,  8.4,  8.4, 25.1, 24.2, 19.2,  9.9,  6.5],
       [ 5. ,  0.7, 30.8,  8.7, 12.8,  9.9, 29.1, 22.1, 33.6],
       [ 5.4, 13.2, 26.8, 17.4,  7.9, 29.2,  6.3,  0.5, 18.1],
       [26.6,  1.5, 29.7, 14.8, 15.1,  7.4, 14.1, 26.4, 30. ],
       [15.9,  6.9, 11.7,  8.6,  7.1, 32.1,  8.9, 24.2,  5.7],
       [12. , 19.2, 29.6, 33.9,  1.6,  4.7, 21.7, 26.5,  5.1]])

In [111]:
# les méthodes mean et sum peuvent être appliquer aux nd arrays
np.mean(array)

158.56666666666666

In [112]:
array.mean
# ici méthode spécifique des ndarray

<function ndarray.mean>

In [113]:
array.min

<function ndarray.min>

In [114]:
array.min()

3

In [115]:
array.max()

339

In [119]:
np.mean(array, axis=0)
# Calcul de la moyenne par colonne

array([149.3, 134.1, 193.8, 174.9, 122.5, 164.4, 151.6, 177.2, 159.3])

In [118]:
np.mean(array, axis=1)
# Calcul de la moyenne par ligne

array([141.88888889, 141.77777778, 188.33333333, 157.22222222,
       158.11111111, 169.66666667, 138.66666667, 184.        ,
       134.55555556, 171.44444444])